require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'vendor/**/*'

Lint/MissingSuper:
  Exclude:
    - 'app/services/*.rb'

Layout/LineLength:
  Max: 100

# This is hard to keep in specs by their nature
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'